### ISSUE TITLE
Separate draft files

### ISSUE THREAD

**Issue by innoflash** [laravel-shift/blueprint#108]
Hey there, before i could think of wiring a PR, whats your take guys on creating separate drafts for different models.

I am thinking if 1 model can have 20 lines of draft, it would mean for a project with just 10 models that`s almost 200 lines of YML. Something tells me its almost a recipe for disaster esp if the project is to grow. 

I was thinking of creating a drafts folder and make a command to create a a draft and run that draft by name.

**Comment by jasonmccreary** [comment]
You can separate draft files if you like. There's no restriction by Blueprint how your store them.

However, you will be responsible for running them in order and maintaining them. Since Blueprint is a _passive_ code generator, there's really no need to keep draft files, unless you wanted to share them with other projects.

That's why I've defaulted Blueprint to simply run against a `draft.yaml` file. It's intended to be a _scratch pad_ of sorts. You just keep reusing it as you generate more and more code.
