### ISSUE TITLE
Add support for package Traits on Models (Potentially Others)

### ISSUE THREAD

**Issue by ahuggins** [laravel-shift/blueprint#212]
### Synopsis:
Spatie and other package devs provide some things in really handy traits. I thought it would be cool to be able to have a `traits` key on a model in the yml and Blueprint could automatically add the `use SomeTrait` and the `use PackageNameSpace\SomeTrait` to the model when it generated.

### Proposed Syntax:

```yml
models:
  Item:
    traits: HasTags, HasMediaTrait
```

### Expected Behavior:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Tags\HasTags;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Item extends Model
{
    use HasTags, HasMediaTrait;
```

### Proposed Proof of Concept
Blueprint works when it is installed on a Laravel application and runs in that context. So if you have whatever package installed...say Spatie Laravel Tags...then that is available in the Composer Class Map. You can filter to any class in the ClassMap that matches, and the key returned would give you the namespace you need. As well as the name of the Trait.

The simplest thing to show this, is something like this:
```php
// Assumes Spatie Laravel Tags is installed to see returned key value pair.
$classMap = collect(require base_path('vendor/composer/autoload_classmap.php'));
$classMap->filter(function ($class, $key) {
     return strpos($key, 'HasTags');
})->dd();;
```

![Screen Shot 2020-05-16 at 5 42 29 PM](https://user-images.githubusercontent.com/1791228/82130796-a9f01f80-979c-11ea-9cda-0b00e55355dd.png)

Obviously strpos only matches if there is exact match. But figure if nothing is matched. Then the trait is not added...OR the `use SomeTrait` is added, but nothing added for the namespace import.

Also, if more than one package or class matches. Then I guess you could use the Laravel Question command method, to ask which trait to use. Or ask if that trait should be generated.

**Comment by jasonmccreary** [comment]
I see the value. But this probably falls into the _gray area_ of things Blueprint shouldn't do.

If it were as simple as this syntax, I might be more open to it. Unfortunately, it's not. Using something like `traits` prevents a column name of `traits.

So the syntax really needs to be something more like.

```yaml
models:
  User:
    meta:
       traits: Notifiable, etc
```

That starts to get pretty verbose and has the same issue (e.g. can't define a column name of `meta`)

As an alternative, there's an open PR for allowing customization of the stubs. So it will soon be possible if all your models use such traits, you could update the `model.stub`.

Sorry to squash the idea. But I'm keeping the fine line between what Blueprint does efficiently, and what's more efficient for a developer to do after generating code.

Otherwise, Blueprint becomes its own language, like TypeScript. 😅

**Comment by ahuggins** [comment]
Ohhh yeah, those keys represent the columns (slipped my mind).

Thanks, I appreciate the thoughtful and timely response. I see your point.

I guess the reason it seemed like a neat idea is that it would let you declare that stuff in one place. Thinking if you did `blueprint:build` and `blueprint:erase` then you have to add it each time while you play around.

What about something like a `_traits`? The likelihood of column collisions would be much less likely I would think. For that matter, anything prepended with `_` could be identifiable as "not a column." Thinking about how `relationships:` is currently a possible collision.

**Comment by jasonmccreary** [comment]
Yeah. All fair points. Maybe something for 2.0. 😉
