### ISSUE TITLE
FR: ability to alias relationships

### ISSUE THREAD

**Issue by edalzell** [laravel-shift/blueprint#294]
### Synopsis:

It's great you can define relationships with standard names, but sometimes I need a relationship to have a different name.

### Proposed Syntax:

`hasOne: User as lead`

### Expected Behavior:

The `hasOne` relationship is created with a `lead()` method.

**Comment by jasonmccreary** [comment]
Currently this is allowed for `belongsTo` relationships by changing the column name, or providing a _reference_. For example, `owner_id: id:User`.

I'd be open to a similar syntax for more complex relationships. For example:

```yaml
models:
  Salesman:
    name: string
    relationships:
        hasOne: Lead:User
```

The trickiest part will be parsing that. But there is precedence within Blueprint. So shouldn't be too hard to implement if you or someone else wants to take a crack.

Otherwise, I'll come back to this in the future if others want it.

**Comment by nathane** [comment]
This syntax `hasOne: {class_name}:{method_name}` is currently supported, to "alias" eloquent relationships.
