### ISSUE TITLE
SoftDeletes Issue

### ISSUE THREAD

**Issue by shepherdscribe** [laravel-shift/blueprint#546]
- Laravel Version: 8.0
- PHP Version: 8.0
- Blueprint Version: 2.2
- Platform: Mac

### Issue:
softDeletes issue on model factory still treats it as string.
<img width="814" alt="Screen Shot 2022-02-16 at 11 04 33 AM" src="https://user-images.githubusercontent.com/62448059/154188301-4d913ff1-522c-4c9e-905b-1ee844af3965.png">

### draft.yaml:
```yaml
# PLEASE PASTE THE DRAFT FILE WHICH REPRODUCES THE ISSUE HERE...
```
Address:
    client_id: unsignedBigInteger foreign:clients
    street: string
    region_id: unsignedInteger
    province_id: unsignedInteger
    city_id: unsignedInteger
    barangay_id: unsignedInteger
    zip_code: unsignedInteger min:3 max:4
    user_id: unsignedBigInteger nullable foreign:users
    type: enum:primary,billing,user default:primary
    softDeletes

**Comment by mgkimsal** [comment]
FWIW, it's still doing this on blueprint 2.3 (as of today)

**Comment by jasonmccreary** [comment]
Very strange. Seems the factory is keeping a literal "softdeletes" column name. Open to PRs. Otherwise, this will probably need to wait until June.

**Comment by mgkimsal** [comment]
@jasonmccreary https://github.com/mgkimsal/blueprint/commit/1d5ca05a51aa295165b2aa84fee04240d7156331

haven't done a specific PR because... the ModelLexerTest breaks

```php
 $model = $actual['models']['Model'];
        $this->assertEquals('Model', $model->name());
        $this->assertTrue($model->usesTimestamps());
        $this->assertTrue($model->usesSoftDeletes());

        $columns = $model->columns();
        $this->assertCount(2, $columns);
        $this->assertEquals('id', $columns['id']->name());
        $this->assertEquals('id', $columns['id']->dataType());
        $this->assertEquals('softdeletes', $columns['softdeletes']->name());
        $this->assertEquals('softDeletes', $columns['softdeletes']->dataType());
        $this->assertEquals([], $columns['id']->modifiers());
```

The assertCount fails - it's not 2 any more, because my patch unset()s the softdeletes column.  This *works* around the Factory bug from above - softdeletes is not treated as a column name.  BUT... the test breaks here.   I would think that you wouldn't want the column to still exist (like 'timestamp' behaviour) and therefore this test should be changed, but again... I'm unsure.  I don't know the innards and intentions that much. 

Can you clarify?  I can change the test assertCount and do a PR (or you can just take my code patch - 2 lines - and fix as you need to).

Thanks!

**Comment by jasonmccreary** [comment]
Please check this was resolved in #565 by targeting `dev-master`. Let me know if so and I'll tag a release.

**Comment by mgkimsal** [comment]
@jasonmccreary I didn't see the same problem appear now.  I'm too early in this project to see if there are any other impacts, but I don't suspect so.

**Comment by jasonmccreary** [comment]
@mgkimsal, good enough for me. I'll tag a patch release shortly.
