### ISSUE TITLE
Make the draft.yaml file generate basic auth framework with a flag

### ISSUE THREAD

**Issue by MattHadfield113** [laravel-shift/blueprint#80]
Just had a thought about this while i was using it -

Would it be worth having draft.yaml able to generated with the basic auth framework for a user (Users Table and password_resets table) as an example of how to use Blueprint, this could be a good reference for users just starting to use blueprint.

This could be an option flag i.e. -auth on the command.

**Comment by jasonmccreary** [comment]
Interesting. But wouldn't this just be passed to `laravel new` command. It takes an `--auth` option.

**Comment by MattHadfield113** [comment]
It could, however that wont bring that into the draft file, my thought being that if a user wants to modify the auth before they generate, they are unable to do so without having to write out everything again. Theres also the chances of things being forgotten in the process.

Also, without this function, would the id:users for example work if you are relating to the users model or would this fail as it is unable to reference and change the existing model ?

**Comment by jasonmccreary** [comment]
I'm not sure I see the need. However, if you want to open a PR that has some kind of `--auth` option to generate what Laravel already gives you, I'd be willing to merge it.

Otherwise, draft files are stand-alone. Would be super easy to share a _gist_ of a draft file containing the default auth definition.
